media_player:
  - platform: universal
    name: Razer Nommo Pro Speakers
    commands:
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.rz_spk_ctl_nommo_power
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.rz_spk_ctl_nommo_power
      select_source:
        service: select.select_option
        target:
          entity_id: select.rz_spk_ctl_nommo_source
        data:
          option: "{{ source }}"
      volume_set:
        service: number.set_value
        target:
          entity_id: number.rz_spk_ctl_nommo_volume
        data:
          value: "{{ volume_level }}"
      volume_mute:
        service: switch.toggle
        target:
          entity_id: switch.rz_spk_ctl_nommo_mute
      select_sound_mode:
        service: select.select_option
        target:
          entity_id: select.rz_spk_ctl_nommo_eq
        data:
          option: "{{ sound_mode }}"
    attributes:
      is_volume_muted: switch.rz_spk_ctl_nommo_mute
      volume_level: number.rz_spk_ctl_nommo_volume
      source_list: select.rz_spk_ctl_nommo_source|options
      source: select.rz_spk_ctl_nommo_source
      state: switch.rz_spk_ctl_nommo_power
      sound_mode: select.rz_spk_ctl_nommo_eq
      sound_mode_list: select.rz_spk_ctl_nommo_eq|options
    device_class: speaker
    unique_id: nommo_speaker_controller