name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      # CHANGEME: Set the filenames of your config files here:
      files: esphome-razer-nommo-pro-speaker-controller.yaml
      # CHANGEME: Set the name of your project here:
      name: ESPHome Razer Nommo Pro Speaker Controller
